version: '3.9'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    tty: true
    ports:
      - '8080:8080'
      - '50000:50000'
    container_name: 'jenkins'
    hostname: 'jenkins.clover.com'
    restart: 'no'
    volumes:
      - /home/cloverhsc/Misc/jenkins:/var/jenkins_home
